[2024-02-15T16:59:45.924+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_fail_dag_2.test_fail_task_2 manual__2024-02-15T16:50:49.438770+00:00 [queued]>
[2024-02-15T16:59:45.965+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_fail_dag_2.test_fail_task_2 manual__2024-02-15T16:50:49.438770+00:00 [queued]>
[2024-02-15T16:59:45.967+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-02-15T16:59:46.027+0000] {taskinstance.py:2191} INFO - Executing <Task(KubernetesPodOperator): test_fail_task_2> on 2024-02-15 16:50:49.438770+00:00
[2024-02-15T16:59:46.051+0000] {standard_task_runner.py:60} INFO - Started process 43 to run task
[2024-02-15T16:59:46.066+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_fail_dag_2', 'test_fail_task_2', 'manual__2024-02-15T16:50:49.438770+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_fail_dag_2.py', '--cfg-path', '/tmp/tmp8l3_lhvu']
[2024-02-15T16:59:46.075+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask test_fail_task_2
[2024-02-15T16:59:46.219+0000] {task_command.py:423} INFO - Running <TaskInstance: test_fail_dag_2.test_fail_task_2 manual__2024-02-15T16:50:49.438770+00:00 [running]> on host test-fail-dag-2-test-fail-task-2-7ehw4bjw
[2024-02-15T16:59:46.493+0000] {pod_generator.py:547} WARNING - Model file  does not exist
[2024-02-15T16:59:46.646+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_fail_dag_2' AIRFLOW_CTX_TASK_ID='test_fail_task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T16:50:49.438770+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-15T16:50:49.438770+00:00'
[2024-02-15T16:59:46.668+0000] {pod.py:926} INFO - Building pod test-fail-task-2-lzds4msp with labels: {'dag_id': 'test_fail_dag_2', 'task_id': 'test_fail_task_2', 'run_id': 'manual__2024-02-15T165049.4387700000-ee5bc9edd', 'kubernetes_pod_operator': 'True', 'try_number': '2'}
[2024-02-15T16:59:46.689+0000] {base.py:83} INFO - Using connection ID 'kubernetes_default' for task execution.
[2024-02-15T16:59:47.760+0000] {pod.py:490} INFO - Found matching pod test-fail-task-2-lzds4msp with labels {'airflow_kpo_in_cluster': 'True', 'airflow_version': '2.8.1', 'dag_id': 'test_fail_dag_2', 'kubernetes_pod_operator': 'True', 'run_id': 'manual__2024-02-15T165049.4387700000-ee5bc9edd', 'task_id': 'test_fail_task_2', 'try_number': '2'}
[2024-02-15T16:59:47.779+0000] {pod.py:491} INFO - `try_number` of task_instance: 2
[2024-02-15T16:59:47.783+0000] {pod.py:492} INFO - `try_number` of pod: 2
[2024-02-15T16:59:47.903+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:49.315+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:50.620+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:51.753+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:52.853+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:54.014+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:55.100+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:56.186+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:57.344+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:58.391+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T16:59:59.462+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:00.599+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:01.751+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:02.852+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:03.935+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:05.010+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:06.074+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:07.193+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:08.369+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:09.491+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:10.774+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:11.907+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:12.988+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:14.294+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:15.490+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:17.001+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:18.288+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:20.243+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:21.622+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:24.101+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:35.408+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:37.388+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:38.535+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:39.837+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:40.961+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:42.337+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:43.495+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:44.661+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:45.886+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:47.126+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:48.486+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:50.276+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:51.802+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:53.507+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:55.253+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:56.772+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:00:58.490+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:00.072+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:01.941+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:03.210+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:05.120+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:18.436+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:20.583+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:21.625+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:22.721+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:24.246+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:25.481+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:26.709+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:27.833+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:28.986+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:30.650+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:32.191+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:33.757+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:34.991+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:36.112+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:37.318+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:38.432+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:39.727+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:40.853+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:42.148+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:43.465+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:44.866+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:46.213+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:47.613+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:01:48.979+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-fail-task-2-lzds4msp
[2024-02-15T17:02:58.843+0000] {pod.py:980} ERROR - (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '80c944f9-6666-44a1-a36e-fdd2da2ff545', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '257f2cd3-dba7-4f47-baa6-49dced15d50c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'aa697f9a-2e34-4d59-a9f7-5a3e00d0d86e', 'Date': 'Thu, 15 Feb 2024 17:02:58 GMT', 'Content-Length': '288'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"events is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"events\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"events"},"code":403}

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 508, in await_pod_start
    self.pod_manager.await_pod_start(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 365, in await_pod_start
    raise PodLaunchFailedException(msg)
airflow.providers.cncf.kubernetes.utils.pod_manager.PodLaunchFailedException: Pod took longer than 120 seconds to start. Check the pod events in kubernetes to determine why.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 551, in execute_sync
    self.await_pod_start(pod=self.pod)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 515, in await_pod_start
    for event in self.pod_manager.read_pod_events(pod).items:
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 680, in read_pod_events
    return self._client.list_namespaced_event(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15205, in list_namespaced_event
    return self.list_namespaced_event_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15320, in list_namespaced_event_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f29d5d1c-36e3-470f-a97f-f3b1dbe82656', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '257f2cd3-dba7-4f47-baa6-49dced15d50c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'aa697f9a-2e34-4d59-a9f7-5a3e00d0d86e', 'Date': 'Thu, 15 Feb 2024 17:02:53 GMT', 'Content-Length': '288'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"events is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"events\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"events"},"code":403}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 731, in _read_pod_events
    for event in self.pod_manager.read_pod_events(pod).items:
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 680, in read_pod_events
    return self._client.list_namespaced_event(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15205, in list_namespaced_event
    return self.list_namespaced_event_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15320, in list_namespaced_event_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '80c944f9-6666-44a1-a36e-fdd2da2ff545', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '257f2cd3-dba7-4f47-baa6-49dced15d50c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'aa697f9a-2e34-4d59-a9f7-5a3e00d0d86e', 'Date': 'Thu, 15 Feb 2024 17:02:58 GMT', 'Content-Length': '288'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"events is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"events\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"events"},"code":403}


[2024-02-15T17:02:58.982+0000] {pod.py:785} INFO - Deleting pod: test-fail-task-2-lzds4msp
[2024-02-15T17:02:59.948+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 508, in await_pod_start
    self.pod_manager.await_pod_start(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 365, in await_pod_start
    raise PodLaunchFailedException(msg)
airflow.providers.cncf.kubernetes.utils.pod_manager.PodLaunchFailedException: Pod took longer than 120 seconds to start. Check the pod events in kubernetes to determine why.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 551, in execute_sync
    self.await_pod_start(pod=self.pod)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 515, in await_pod_start
    for event in self.pod_manager.read_pod_events(pod).items:
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 680, in read_pod_events
    return self._client.list_namespaced_event(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15205, in list_namespaced_event
    return self.list_namespaced_event_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15320, in list_namespaced_event_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f29d5d1c-36e3-470f-a97f-f3b1dbe82656', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '257f2cd3-dba7-4f47-baa6-49dced15d50c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'aa697f9a-2e34-4d59-a9f7-5a3e00d0d86e', 'Date': 'Thu, 15 Feb 2024 17:02:53 GMT', 'Content-Length': '288'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"events is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"events\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"events"},"code":403}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 534, in execute
    return self.execute_sync(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 574, in execute_sync
    self.cleanup(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 715, in cleanup
    raise AirflowException(
airflow.exceptions.AirflowException: Pod test-fail-task-2-lzds4msp returned a failure.
remote_pod: {'api_version': None,
 'kind': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': {'airflow_kpo_in_cluster': 'True',
                         'airflow_version': '2.8.1',
                         'dag_id': 'test_fail_dag_2',
                         'kubernetes_pod_operator': 'True',
                         'run_id': 'manual__2024-02-15T165049.4387700000-ee5bc9edd',
                         'task_id': 'test_fail_task_2',
                         'try_number': '2'},
              'managed_fields': [{'api_version': 'v1',
                                  'fields_type': 'FieldsV1',
                                  'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                            'f:airflow_kpo_in_cluster': {},
                                                                            'f:airflow_version': {},
                                                                            'f:dag_id': {},
                                                                            'f:kubernetes_pod_operator': {},
                                                                            'f:run_id': {},
                                                                            'f:task_id': {},
                                                                            'f:try_number': {}}},
                                                'f:spec': {'f:affinity': {},
                                                           'f:containers': {'k:{"name":"base"}': {'.': {},
                                                                                                  'f:image': {},
                                                                                                  'f:imagePullPolicy': {},
                                                                                                  'f:name': {},
                                                                                                  'f:resources': {'.': {},
                                                                                                                  'f:limits': {'.': {},
                                                                                                                               'f:memory': {}},
                                                                                                                  'f:requests': {'.': {},
                                                                                                                                 'f:memory': {}}},
                                                                                                  'f:terminationMessagePath': {},
                                                                                                  'f:terminationMessagePolicy': {}}},
                                                           'f:dnsPolicy': {},
                                                           'f:enableServiceLinks': {},
                                                           'f:restartPolicy': {},
                                                           'f:schedulerName': {},
                                                           'f:securityContext': {},
                                                           'f:terminationGracePeriodSeconds': {}}},
                                  'manager': 'OpenAPI-Generator',
                                  'operation': 'Update',
                                  'subresource': None,
                                  'time': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal())}],
              'name': 'test-fail-task-2-lzds4msp',
              'namespace': 'default',
              'owner_references': None,
              'resource_version': '21301',
              'self_link': None,
              'uid': '5afded8b-c399-4702-b359-44ad7c7e5d06'},
 'spec': {'active_deadline_seconds': None,
          'affinity': {'node_affinity': None,
                       'pod_affinity': None,
                       'pod_anti_affinity': None},
          'automount_service_account_token': None,
          'containers': [{'args': None,
                          'command': None,
                          'env': None,
                          'env_from': None,
                          'image': 'bad_image_sudiptob2:latest',
                          'image_pull_policy': 'Always',
                          'lifecycle': None,
                          'liveness_probe': None,
                          'name': 'base',
                          'ports': None,
                          'readiness_probe': None,
                          'resources': {'limits': {'memory': '200Mi'},
                                        'requests': {'memory': '100Mi'}},
                          'security_context': None,
                          'startup_probe': None,
                          'stdin': None,
                          'stdin_once': None,
                          'termination_message_path': '/dev/termination-log',
                          'termination_message_policy': 'File',
                          'tty': None,
                          'volume_devices': None,
                          'volume_mounts': [{'mount_path': '/var/run/secrets/kubernetes.io/serviceaccount',
                                             'mount_propagation': None,
                                             'name': 'kube-api-access-wkmrh',
                                             'read_only': True,
                                             'sub_path': None,
                                             'sub_path_expr': None}],
                          'working_dir': None}],
          'dns_config': None,
          'dns_policy': 'ClusterFirst',
          'enable_service_links': True,
          'ephemeral_containers': None,
          'host_aliases': None,
          'host_ipc': None,
          'host_network': None,
          'host_pid': None,
          'hostname': None,
          'image_pull_secrets': None,
          'init_containers': None,
          'node_name': 'kind-worker',
          'node_selector': None,
          'os': None,
          'overhead': None,
          'preemption_policy': 'PreemptLowerPriority',
          'priority': 0,
          'priority_class_name': None,
          'readiness_gates': None,
          'restart_policy': 'Never',
          'runtime_class_name': None,
          'scheduler_name': 'default-scheduler',
          'security_context': {'fs_group': None,
                               'fs_group_change_policy': None,
                               'run_as_group': None,
                               'run_as_non_root': None,
                               'run_as_user': None,
                               'se_linux_options': None,
                               'seccomp_profile': None,
                               'supplemental_groups': None,
                               'sysctls': None,
                               'windows_options': None},
          'service_account': 'default',
          'service_account_name': 'default',
          'set_hostname_as_fqdn': None,
          'share_process_namespace': None,
          'subdomain': None,
          'termination_grace_period_seconds': 30,
          'tolerations': [{'effect': 'NoExecute',
                           'key': 'node.kubernetes.io/not-ready',
                           'operator': 'Exists',
                           'toleration_seconds': 300,
                           'value': None},
                          {'effect': 'NoExecute',
                           'key': 'node.kubernetes.io/unreachable',
                           'operator': 'Exists',
                           'toleration_seconds': 300,
                           'value': None}],
          'topology_spread_constraints': None,
          'volumes': [{'aws_elastic_block_store': None,
                       'azure_disk': None,
                       'azure_file': None,
                       'cephfs': None,
                       'cinder': None,
                       'config_map': None,
                       'csi': None,
                       'downward_api': None,
                       'empty_dir': None,
                       'ephemeral': None,
                       'fc': None,
                       'flex_volume': None,
                       'flocker': None,
                       'gce_persistent_disk': None,
                       'git_repo': None,
                       'glusterfs': None,
                       'host_path': None,
                       'iscsi': None,
                       'name': 'kube-api-access-wkmrh',
                       'nfs': None,
                       'persistent_volume_claim': None,
                       'photon_persistent_disk': None,
                       'portworx_volume': None,
                       'projected': {'default_mode': 420,
                                     'sources': [{'config_map': None,
                                                  'downward_api': None,
                                                  'secret': None,
                                                  'service_account_token': {'audience': None,
                                                                            'expiration_seconds': 3607,
                                                                            'path': 'token'}},
                                                 {'config_map': {'items': [{'key': 'ca.crt',
                                                                            'mode': None,
                                                                            'path': 'ca.crt'}],
                                                                 'name': 'kube-root-ca.crt',
                                                                 'optional': None},
                                                  'downward_api': None,
                                                  'secret': None,
                                                  'service_account_token': None},
                                                 {'config_map': None,
                                                  'downward_api': {'items': [{'field_ref': {'api_version': 'v1',
                                                                                            'field_path': 'metadata.namespace'},
                                                                              'mode': None,
                                                                              'path': 'namespace',
                                                                              'resource_field_ref': None}]},
                                                  'secret': None,
                                                  'service_account_token': None}]},
                       'quobyte': None,
                       'rbd': None,
                       'scale_io': None,
                       'secret': None,
                       'storageos': None,
                       'vsphere_volume': None}]},
 'status': {'conditions': [{'last_probe_time': None,
                            'last_transition_time': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal()),
                            'message': None,
                            'reason': None,
                            'status': 'True',
                            'type': 'PodScheduled'}],
            'container_statuses': None,
            'ephemeral_container_statuses': None,
            'host_ip': None,
            'init_container_statuses': None,
            'message': None,
            'nominated_node_name': None,
            'phase': 'Pending',
            'pod_i_ps': None,
            'pod_ip': None,
            'qos_class': 'Burstable',
            'reason': None,
            'start_time': None}}
[2024-02-15T17:03:00.067+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_fail_dag_2, task_id=test_fail_task_2, execution_date=20240215T165049, start_date=20240215T165945, end_date=20240215T170300
[2024-02-15T17:03:00.484+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task test_fail_task_2 (Pod test-fail-task-2-lzds4msp returned a failure.
remote_pod: {'api_version': None,
 'kind': None,
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': {'airflow_kpo_in_cluster': 'True',
                         'airflow_version': '2.8.1',
                         'dag_id': 'test_fail_dag_2',
                         'kubernetes_pod_operator': 'True',
                         'run_id': 'manual__2024-02-15T165049.4387700000-ee5bc9edd',
                         'task_id': 'test_fail_task_2',
                         'try_number': '2'},
              'managed_fields': [{'api_version': 'v1',
                                  'fields_type': 'FieldsV1',
                                  'fields_v1': {'f:metadata': {'f:labels': {'.': {},
                                                                            'f:airflow_kpo_in_cluster': {},
                                                                            'f:airflow_version': {},
                                                                            'f:dag_id': {},
                                                                            'f:kubernetes_pod_operator': {},
                                                                            'f:run_id': {},
                                                                            'f:task_id': {},
                                                                            'f:try_number': {}}},
                                                'f:spec': {'f:affinity': {},
                                                           'f:containers': {'k:{"name":"base"}': {'.': {},
                                                                                                  'f:image': {},
                                                                                                  'f:imagePullPolicy': {},
                                                                                                  'f:name': {},
                                                                                                  'f:resources': {'.': {},
                                                                                                                  'f:limits': {'.': {},
                                                                                                                               'f:memory': {}},
                                                                                                                  'f:requests': {'.': {},
                                                                                                                                 'f:memory': {}}},
                                                                                                  'f:terminationMessagePath': {},
                                                                                                  'f:terminationMessagePolicy': {}}},
                                                           'f:dnsPolicy': {},
                                                           'f:enableServiceLinks': {},
                                                           'f:restartPolicy': {},
                                                           'f:schedulerName': {},
                                                           'f:securityContext': {},
                                                           'f:terminationGracePeriodSeconds': {}}},
                                  'manager': 'OpenAPI-Generator',
                                  'operation': 'Update',
                                  'subresource': None,
                                  'time': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal())}],
              'name': 'test-fail-task-2-lzds4msp',
              'namespace': 'default',
              'owner_references': None,
              'resource_version': '21301',
              'self_link': None,
              'uid': '5afded8b-c399-4702-b359-44ad7c7e5d06'},
 'spec': {'active_deadline_seconds': None,
          'affinity': {'node_affinity': None,
                       'pod_affinity': None,
                       'pod_anti_affinity': None},
          'automount_service_account_token': None,
          'containers': [{'args': None,
                          'command': None,
                          'env': None,
                          'env_from': None,
                          'image': 'bad_image_sudiptob2:latest',
                          'image_pull_policy': 'Always',
                          'lifecycle': None,
                          'liveness_probe': None,
                          'name': 'base',
                          'ports': None,
                          'readiness_probe': None,
                          'resources': {'limits': {'memory': '200Mi'},
                                        'requests': {'memory': '100Mi'}},
                          'security_context': None,
                          'startup_probe': None,
                          'stdin': None,
                          'stdin_once': None,
                          'termination_message_path': '/dev/termination-log',
                          'termination_message_policy': 'File',
                          'tty': None,
                          'volume_devices': None,
                          'volume_mounts': [{'mount_path': '/var/run/secrets/kubernetes.io/serviceaccount',
                                             'mount_propagation': None,
                                             'name': 'kube-api-access-wkmrh',
                                             'read_only': True,
                                             'sub_path': None,
                                             'sub_path_expr': None}],
                          'working_dir': None}],
          'dns_config': None,
          'dns_policy': 'ClusterFirst',
          'enable_service_links': True,
          'ephemeral_containers': None,
          'host_aliases': None,
          'host_ipc': None,
          'host_network': None,
          'host_pid': None,
          'hostname': None,
          'image_pull_secrets': None,
          'init_containers': None,
          'node_name': 'kind-worker',
          'node_selector': None,
          'os': None,
          'overhead': None,
          'preemption_policy': 'PreemptLowerPriority',
          'priority': 0,
          'priority_class_name': None,
          'readiness_gates': None,
          'restart_policy': 'Never',
          'runtime_class_name': None,
          'scheduler_name': 'default-scheduler',
          'security_context': {'fs_group': None,
                               'fs_group_change_policy': None,
                               'run_as_group': None,
                               'run_as_non_root': None,
                               'run_as_user': None,
                               'se_linux_options': None,
                               'seccomp_profile': None,
                               'supplemental_groups': None,
                               'sysctls': None,
                               'windows_options': None},
          'service_account': 'default',
          'service_account_name': 'default',
          'set_hostname_as_fqdn': None,
          'share_process_namespace': None,
          'subdomain': None,
          'termination_grace_period_seconds': 30,
          'tolerations': [{'effect': 'NoExecute',
                           'key': 'node.kubernetes.io/not-ready',
                           'operator': 'Exists',
                           'toleration_seconds': 300,
                           'value': None},
                          {'effect': 'NoExecute',
                           'key': 'node.kubernetes.io/unreachable',
                           'operator': 'Exists',
                           'toleration_seconds': 300,
                           'value': None}],
          'topology_spread_constraints': None,
          'volumes': [{'aws_elastic_block_store': None,
                       'azure_disk': None,
                       'azure_file': None,
                       'cephfs': None,
                       'cinder': None,
                       'config_map': None,
                       'csi': None,
                       'downward_api': None,
                       'empty_dir': None,
                       'ephemeral': None,
                       'fc': None,
                       'flex_volume': None,
                       'flocker': None,
                       'gce_persistent_disk': None,
                       'git_repo': None,
                       'glusterfs': None,
                       'host_path': None,
                       'iscsi': None,
                       'name': 'kube-api-access-wkmrh',
                       'nfs': None,
                       'persistent_volume_claim': None,
                       'photon_persistent_disk': None,
                       'portworx_volume': None,
                       'projected': {'default_mode': 420,
                                     'sources': [{'config_map': None,
                                                  'downward_api': None,
                                                  'secret': None,
                                                  'service_account_token': {'audience': None,
                                                                            'expiration_seconds': 3607,
                                                                            'path': 'token'}},
                                                 {'config_map': {'items': [{'key': 'ca.crt',
                                                                            'mode': None,
                                                                            'path': 'ca.crt'}],
                                                                 'name': 'kube-root-ca.crt',
                                                                 'optional': None},
                                                  'downward_api': None,
                                                  'secret': None,
                                                  'service_account_token': None},
                                                 {'config_map': None,
                                                  'downward_api': {'items': [{'field_ref': {'api_version': 'v1',
                                                                                            'field_path': 'metadata.namespace'},
                                                                              'mode': None,
                                                                              'path': 'namespace',
                                                                              'resource_field_ref': None}]},
                                                  'secret': None,
                                                  'service_account_token': None}]},
                       'quobyte': None,
                       'rbd': None,
                       'scale_io': None,
                       'secret': None,
                       'storageos': None,
                       'vsphere_volume': None}]},
 'status': {'conditions': [{'last_probe_time': None,
                            'last_transition_time': datetime.datetime(2024, 2, 15, 16, 59, 47, tzinfo=tzlocal()),
                            'message': None,
                            'reason': None,
                            'status': 'True',
                            'type': 'PodScheduled'}],
            'container_statuses': None,
            'ephemeral_container_statuses': None,
            'host_ip': None,
            'init_container_statuses': None,
            'message': None,
            'nominated_node_name': None,
            'phase': 'Pending',
            'pod_i_ps': None,
            'pod_ip': None,
            'qos_class': 'Burstable',
            'reason': None,
            'start_time': None}}; 43)
[2024-02-15T17:03:01.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-15T17:03:01.655+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
